EpiModel/EpiModel

- R/control.R
- R/netsim.R
- man/control.net.Rd
- man/netsim.Rd
- tests/testthat/test-newnet.R
> Module reordering for netsim

- R/control.R
- R/net.mod.init.R
- man/control.net.Rd
- tests/testthat/test-netpids.R
> Consistent handling of PIDs in network models

- R/dcm.R
- R/dcm.mods.R
- R/plot.R
- R/test.R
- tests/testthat/test-dcm.R
- tests/testthat/test-net-long.R
- tests/testthat/test-netsim.R
- tests/testthat/test-newdcm.R
> Fix DCM flows

- R/plot.R
- man/plot.icm.Rd
- man/plot.netdx.Rd
- tests/testthat/test-netdx.R
> General plot updates

- inst/shiny/epinet/server.R
- inst/shiny/epinet/ui.R
> concurrency slider min in epinet app

- R/dendo.R
- man/as.phylo.transmat.Rd
- tests/testthat/test-transmat-dendo.R
* fixes a bug where vertex.exit.times were not correctly translated to phylo edge durations for some transmission matrices
* added support for transmission matrices with multiple seeds (a list of phylo objects, one for each seed is returned)
> additional phylo tree updates

- R/plot.R
- R/verbose.R
Much cleaner, and now correctly processes net plots with `epi.by` prevalence data
> Major fix to denom plot helper function

- R/netsim.R
> Allow net sims of 1 time step

- .travis.yml
- R/plot.R
- man/plot.netsim.Rd
Changed plot.netsim to match CVM plot.netdx code.
> Make plot.netsim formation plots consistent with plot.netdx

- R/plot.R
- man/plot.netdx.Rd
Lowess smoothing is default plotting with option of overlaying individual simulation results over this. No updated unit test as I'm not sure how this change can error out.
> Changed default plotting behavior for dyanmic=FALSE network diagnostic plotting

- R/netdx.R
- tests/testthat/test-netdx.R
> Cross sectional ergm netdx dynamic error

- R/get.R
- R/net.inputs.R
- R/net.utils.R
- R/plot.R
- R/saveout.R
- man/color_tea.Rd
- man/control.net.Rd
- man/get_network.Rd
- tests/testthat/test-net-long.R
- tests/testthat/test-transmat-dendo.R
Issue: "tergmLite replaces save.network and save.transmat. If FALSE, then save these two things. If TRUE, don't save them."
> Save network and transmission matrix

- R/plot.R
- R/print.r
- man/merge.netsim.Rd
Update to print and plot function. ```print.netsim```: requested formatting changes. ```plot```: color assignment based on number of epi stats plotted; colors now assigned by class of stat instead of unique colors for each stat.
> printplot: Update to multiple group plotting and format of print.

- tests/testthat/test-net-long.R
- tests/testthat/test-newnet.R
Debugging of test_net( ) function on R development branch (R release 4.0, daily test branch).
> test_net( ): testing on dev branch.

- .travis.yml
- R/get.R
- R/net.mod.infection.R
- R/net.mod.init.R
- R/net.mod.nwupdate.R
- R/net.mod.simnet.R
- R/net.utils.R
- R/saveout.R
- man/discord_edgelist.Rd
- man/get_network.Rd
- man/nwupdate.net.Rd
- tests/testthat/test-attr-copy.R
- tests/testthat/test-net-long.R
Update of network on dat object (dat$nw) to use more flexible language: dat$nw[[1]].
> EpiModel: Update to network object syntax

- man/discord_edgelist.Rd
- tests/testthat/test-newmodules.R
Add's unit tests for new user modules. Addresses #360
> Addition of unit-test for module extension

- R/net.dat.R
Updated "$" syntax in net.dat.R to brackets for consistency; was curious as well if we want to use accessor functions themselves.
> Accessor Consistency

- R/netsim.R
Correct https://github.com/statnet/EpiModel/issues/456#issuecomment-708584233
> Create a temporary `at` for initialization step

- R/net.mod.infection.R
- man/discord_edgelist.Rd
- man/set_transmat.Rd
> Add infstat param to discord_edgelist

- R/net.mod.simnet.R
- tests/testthat/test-net-tergmLite.R
> Allow tergmLite with duration = 1 models

- R/plot.R
- man/plot.netsim.Rd
> Flexible vertex.cex in plot.netsim

- R/net.inputs.R
- R/saveout.R
- tests/testthat/test-netsim.R
> Reallow save.network in control.net

- R/net.mod.infection.R
> fixes issue 563 (set_transmat function bug)

- vignettes/Intro.Rmd
- vignettes/working-with-network-objects.Rmd
> el_cuml vignette draft

- NEWS.md
- R/el_cuml.R
- man/get_partners.Rd
- vignettes/network-objects.Rmd
- `max.age` -> `truncate`
- `only.active` -> `only.active.nodes`
vignettes and NEWS are updated accordingly
#628
> `get_partners` better parameter names

- tests/testthat/test-net-tergmLite.R
> add tergmLite test for edgecov term

- DESCRIPTION
- R/dendo.R
- man/as.network.transmat.Rd
- man/as.phylo.transmat.Rd
- man/plot.transmat.Rd
fixes #659 
I added back ndtv as a suggest, re-implemented the "transmissionTimeline" style by reusing the code that was removed in [this commit](https://github.com/EpiModel/EpiModel/commit/745ad46ace430bbe8334f82c22c6004c44fa26b3).
I tested against the NME d3-s8 script and it works fine
> add ndtv back

- NEWS.md
I don't have push access to `main` so this is in the form of a PR.
Includes NEWS updates for PRs of mine that have been merged since the last push to CRAN, plus a couple of notes about the dissolution changes in #592.  (Does not include NEWS updates for all the other stuff that other people have been doing.)
> news updates for recent PRs and dissolution changes

- NEWS.md
@smjenness 
I updated NEWS for the 2 PRs on which I forgot to do it: #683 #641
> reflect other PRs in NEWS

- R/merge.R
- man/merge.netsim.Rd
- tests/testthat/test-merge.R
for consistency with other cases.  Also remove vestigial keep.summary.stats argument to merge.netsim.
closes #720
> update keep.transmat logic in merge.netsim

- R/get.R
- tests/testthat/test-get.R
> handle diss.stats in get_sims

- R/network.R
- inst/JSS/EpiModelJSS2.R
- man/network_initialize.Rd
- tests/testthat/test-net-long.R
- tests/testthat/test-net-tergmLite.R
- tests/testthat/test-networkLite.R
> remove directed, bipartite, etc. arguments from network_initialize

- NEWS.md
- R/get.R
- R/merge.R
- R/saveout.R
- tests/testthat/test-netsim.R
> save.other sim names

- R/saveout.R
> drop indices when naming transmat

- NEWS.md
> misc NEWS updates

- NEWS.md
- R/netsim.R
do all parallel activity in one call
> Fix the parallel memory leak

- NEWS.md
- R/net.inputs.R
> use scenario tools for random params

- R/saveout.R
Making this as a separate PR since `multinets` itself may not be merged into `main` for some time.
references EpiModel/EpiModelHIV-p#166
> update ess calculation in saveout.net to work with multiple networks

- R/netest.R
- tests/testthat/test-netest.R
- tests/testthat/test-netsim.R
to avoid a new warning in statnet.common
closes #782
> pass environment to append_rhs.formula

- tests/testthat/test-networkLite.R
> update networkLite tests for changes to CRAN network

- R/el_cuml.R
- R/get.R
- R/net.inputs.R
- R/net.mod.infection.R
- R/net.mod.init.R
- R/net.mod.nwupdate.R
- R/net.mod.simnet.R
- R/net.mod.summary.R
- R/net.utils.R
- R/saveout.R
- tests/testthat/test-multinets.R
> add num.nw field to dat object

- NEWS.md
- R/icm.mod.init.R
- R/icm.mod.status.R
- R/icm.utils.R
- R/saveout.R
- R/verbose.R
- man/arrivals.icm.Rd
- man/arrivals.icm.bip.Rd
- man/departures.icm.Rd
- man/departures.icm.bip.Rd
- man/infection.icm.Rd
- man/infection.icm.bip.Rd
- man/init_status.icm.Rd
- man/initialize.icm.Rd
- man/prevalence.icm.Rd
- man/prevalence.icm.bip.Rd
- man/recovery.icm.Rd
- man/recovery.icm.bip.Rd
- man/saveout.icm.Rd
- man/verbose.icm.Rd
> class icm dat object as icm_dat; update documentation

- .lintr
- R/ErgmTerms.R
- R/dcm.R
- R/dcm.inputs.R
- R/dendo.R
- R/get.R
- R/icm.inputs.R
- R/icm.mod.status.R
- R/merge.R
- R/net.accessor.R
- R/net.end.horizon.R
- R/net.fn.modules.R
- R/net.inputs.R
- R/net.mod.prevalence.R
- R/net.mod.simnet.R
- R/net.mod.summary.R
- R/net.scenarios.R
- R/net.utils.R
- R/netdx.R
- R/netsim.R
- R/netsim_checkpoint.R
- R/plot.R
- R/print.R
- R/saveout.R
- R/summary.R
- R/utils.R
Lintr [3.1.0 release](https://github.com/r-lib/lintr/releases/tag/v3.1.0) use the `skip_with` argument needed to fix #750 
It will take some time for the github action to update to this new version though
> Test with linter3.1.0

- R/plot.epi.data.frame.R
fixes #908 
sorry for that, I messed up my last commit on `plot`
> fix arg name

- R/dcm.inputs.R
- R/dendo.R
- R/netdx.R
- R/netest.R
- R/plot.dcm.R
- R/plot.netsim.R
- R/print.R
- R/utils.R
- man/as.network.transmat.Rd
- man/as.phylo.transmat.Rd
- man/brewer_ramp.Rd
- man/control.dcm.Rd
- man/netdx.Rd
- man/plot.dcm.Rd
- man/plot.netsim.Rd
- man/plot.transmat.Rd
- man/print.netdx.Rd
- man/tedgelist_to_toggles.Rd
> fixes the anchors in documentation

- NEWS.md
- R/plot.netsim.R
> correctly pass ellipsis to plot call

- R/plot.R
> correct x values for polygon

- DESCRIPTION
- R/plot.icm.R
- R/shiny.R
- inst/shiny/epidcm/server.R
- inst/shiny/epidcm/ui.R
- inst/shiny/epiicm/server.R
- inst/shiny/epiicm/ui.R
- inst/shiny/epinet/server.R
- inst/shiny/epinet/ui.R
- man/epiweb.Rd
Closes #926 
Fixes issue in `plot.icm` where `sim.alpha` was turned into logical if `nsims == 1`.
> Fix shiny and plot.icm issues
