EpiModel/EpiModel

R/net.utils.R

Edit to internal function get_formula_terms to allow multiple offset terms in network formation formula.

Allow multiple offset terms

---

R/plot.R

The na.rm=TRUE option was not specified in the draw_means helper function when getting the min and max mean value for specified plot terms. As a result, an error message was received explaining that there was an unspecified ylim when plotting. NA values were being returned as the mean min and max before being set as the ylim lower and upper bound. This is not an issue in the draw_qnts as NA values are dealt with using na.rm in the main body of the function, and was only an issue in draw_means when nsims=1.

Update R/plot.R - Add na.rm option to draw_means helper function

---

R/plot.R

The plot.netsim function originally displayed three specified plot variables when mean.col and qnts.col were not user-specified due to hardcoding of the color palette for three colors.
Combined "Set1", "Set2", and "Set3" color brewer palettes for the fix to allow the max number of plotted variables to be 29 when user does not specify mean.col or qnts.col.
Resolves Issue #325

Update plot.R - plot.netsim color palette

---

R/netsim.R

Creation of a `netsim.loop` function containing the duplicated code for
mono and multicore in `netsim`.
Modified-by: Adrien Le Guillou <adrien.leguillou@gmail.com>

Deduplication of the simulation code of netsim function

---

R/merge.R

Update of merge.netsim documentation to make it clear when transmission matrices and network are saved as well as which parameter controls this behavior.

Update merge.netsim documentation

---

R/net.inputs.R
man/control.net.Rd
man/merge.netsim.Rd
tests/testthat/test-attr-copy.R
tests/testthat/test-net-tergmLite.R

Adds unit tests for basic tergmLite usage as well as for attribute copying between network and data attribute lists.

Add unit tests for tL and attribute copying

---

R/net.mod.prevalence.R

With EpiModel 2.0, if a user specifies and user defined functions, type must be set to NULL. This fixes an error in the prev. functions when this is the case.

Fix prevalence functions: type = NULL.

---

R/net.inputs.R
R/print.r

Output from `print.netsim` has been updated to be more flexible and account for base and user extended modules. Previous versions of pulling function names was largely hard coded; this has been completely removed. Now, `f.args` and `f.names` are pulled during `control.net` and updated during `crosscheck.net`. If any functions are missing (NA in `f.args`) these are dropped, maintaining those functions present in control inputs. Note: any user defined function names are parsed as `function` off of `function.FUN`.
Addresses #431 .

Update to print.netsim.

---

R/get.R
R/merge.R
R/net.inputs.R
R/saveout.R
man/control.net.Rd
man/merge.netsim.Rd
tests/testthat/test-net-tergmLite.R
tests/testthat/test-transmat-dendo.R

Closes #451
EpiModel updated to allow saving of transmission matrix independent of tergmLite setting:
```
num <- 100
nw <- network_initialize(num)
coef.diss <- dissolution_coefs(dissolution = ~offset(edges),
duration = 20)
est <- netest(nw, formation = ~edges, target.stats = 40, coef.diss)
param <- param.net(inf.prob = 0.4, act.rate = 1)
init <- init.net(i.num = 10)
control <- control.net(type = "SI", nsteps = 10, resimulate.network = TRUE,
tergmLite = TRUE, save.transmat = TRUE)
```

Allow saving of transmission matrix

---

R/net.accessor.R
man/unique_id-tools.Rd

Small complement to the `get_unique_ids` /  `get_posit_ids` functions.
now if the argument `unique_ids` or `posit_ids` is NULL (default value) the functions will return the full vector of positional IDs or unique IDs respectively

get all unique / posit IDs

---

R/net.mod.init.R
R/net.mod.simnet.R

closes #551
removes redundant nwstats setup from initialize.net and drops duplicated statistics in resim_nets
requires a test update in tergmLite which will be a separate PR to be opened shortly

nwstats update

---

.Rbuildignore
.gitignore
R/net.inputs.R
R/print.r
man/generate_random_params.Rd
tests/testthat/test-random-params.R
vignettes/Random-parameterization-interface.Rmd

Initial implementation to close #533 using the `param_random_set` approach.
the following code works:
```r
pkgload::load_all("../EpiModel")
nw <- network_initialize(n = 100)
formation <- ~edges
target.stats <- 50
coef.diss <- dissolution_coefs(dissolution = ~offset(edges), duration = 20)
est <- netest(nw, formation, target.stats, coef.diss, verbose = FALSE)
generate_correlated_params <- function() {
param.unique <- runif(1)
param.set.1 <- param.unique + runif(2)
param.set.2 <- param.unique * rnorm(3)
return(list(param.unique, param.set.1, param.set.2))
}
correlated_params <- t(replicate(10, unlist(generate_correlated_params())))
correlated_params <- as.data.frame(correlated_params)
colnames(correlated_params) <- c(
"param.unique",
"param.set.1_1","param.set.1_2",
"param.set.2_1", …
```

 Allow random parameters to be generated from correlated distribution (fixes #533) 

---

R/get.R
tests/testthat/test-get.R
vignettes/model-parameters.Rmd

fixes #603 
- `get_param_set` no longer prints the random parameters twice and now displays the correct values.
- the "model parameters" vignettes now uses `get_param_set`
- the tests of `get_param_set` are now correctly detecting when the data.frame is malformed

Fix603 get_param_set

---

vignettes/attributes-and-summary-statistics.Rmd

In the summary and attribute vignette, "status" was stored with the attribute history API but "switch_status" was displayed when accessing it afterwards.

switch_status -> status

---

R/print.r

fix #600 by removing the unused code and by printing "module.order" for
the module used when it is not `NULL`

Simplify `print.control.net`

---

NEWS.md
vignettes/model-parameters.Rmd

Should I also modify the "Working with model parameters" vignette to add a section covering the control updaters?
Maybe "## (Advanced) Time-Varying Controls" with a succinct example as the mecanisms are the same as for Time-Varying Parameters

Mention control_updater in NEWS

---

R/el_cuml.R
R/net.inputs.R
R/net.mod.nwupdate.R
man/control.net.Rd
man/get_partners.Rd
man/nwupdate.net.Rd
man/update_cumulative_edgelist.Rd

This changes the default of cumulative edgelist storage to FALSE, and the default truncation to 0 (current edges only). Additionally, I added cumulative.edgelist and truncate.el.cuml as explicit args in control.net. 
@AdrienLeGuillou Could you check this PR?

Change defaults of cuml el, add explicit args

---

.gitignore
R/net.accessor.R

this PR prevents an error from occurring when passing an empty numeric vector as the `posit_ids` arguments of `set_attr` and `get_attr`
Now `set_attr` will return an unmodified `dat` object in this case. Similar to base R behavior:
``` 
x <- 1:10
x[numeric(0)] <- 2
x
#> [1]  1  2  3  4  5  6  7  8  9 10
```
and `get_attr` will return an empty vector of the right type. As if we called:
```
dat$attr$target_attr[numeric(0)]
```
These behavior allows the module author to work with vector of IDs without checking if they are empty or not

Fix empty positids

---

R/merge.R
R/net.inputs.R
R/plot.R
R/print.r
R/saveout.R
man/control.net.Rd
man/merge.netsim.Rd
tests/testthat/test-merge.R
tests/testthat/test-netsim.R

stacked on #702
closes #713, #719
(optionally) stores diss stats on returned netsim object for later plotting, printing
also tweaks a couple of things to more consistently handle netsim fields dropped in merge (cf #719)

nonstochastic netsim plots

---

R/get.R
R/merge.R
tests/testthat/test-get.R

should now always come back as `paste0("sim", seq_len(nsims))`
also simplified logic in `merge.netsim` a bit, using `c` for `list`s
closes #722

`get_sims` and `merge.netsim` sim names

---

NEWS.md
R/netest.R
man/netest.Rd

I previously added default control arguments to `netdx`, in part to illustrate the required control classes.  This does the same for `netest`, and updates the NEWS file.

netest default controls

---

NEWS.md
R/el_cuml.R
tests/testthat/test-cumulative_edgelist.R

`get_edglists` and `get_cumulative_edgelists` now error when the network
argument refers to a non existing network
related to this issue https://github.com/EpiModel/EpiModelHIV-p/issues/124

edglists functions informative errors

---

R/net.accessor.R
tests/testthat/test-accessors.R

refactor `set_epi` and `add_epi` to use a generic `padded_vector` function that can be used by `nwstats` or `transmat` for instance.
Also put `epi` by default to `NA_real_` as they are more often numeric than logical

create a generic padded_vector function

---

R/el_cuml.R
R/net.mod.simnet.R

Fixes issues that prevented this EpiModel Gallery example from running:
https://github.com/EpiModel/EpiModel-Gallery/tree/main/2018-08-ObservedNetworkData
* `get_edgelist` stop check no longer uses `dat$param`
* `resim_nets` avoids unnecessary pulls of control settings if `resimulate.network = FALSE`

Fixes minor issues for working with observed network data

---

NEWS.md
R/net.inputs.R

in `control.net` `message` is called with a `call.` argument. As it is not a named argument to `message`, the value is concatenated to the message string.
fixes #780

remove the `call.` argument to `message`

---

R/net.scenarios.R
tests/testthat/test-random-params.R

- some of the rng params test where malformed they were adding duplicated params where they shouldn't. Triggering warnings that are tested elsewhere
- the check_scenario_df function was letting a warning pass due to poor ordering of the checks

fix rng and scenarios tests

---

NEWS.md
R/saveout.R
tests/testthat/test-netsim.R

Changes the behavior of `saveout.net` on the last sim of a batch. It now tries to rename the elements if there number match the number of simulation. In case of missmatch, a warning is produced.
addresses #790

Prevent errors when missing elements are saved

---

NEWS.md
R/get.R
tests/testthat/test-record.R

- using `dplyr::as_tibble` fixes it automatically
- addition of a specific test for the 0 length case

 Fix error where `get_attr_history` would crash on length zero PIDs 

---

DESCRIPTION
tests/testthat/test-ergm.ego.R
tests/testthat/test-netdx.R
tests/testthat/test-netest.R

When I run `testthat::test_package()` on EpiModel, this triggers this Warning:
```r
── Warning (Line 27): environment handling in non-nested EDA ───────────────────
Argument(s) ‘from.new’ were not recognized or used. Did you mistype an argument name?
Backtrace:
1. EpiModel::netest(...)
24. rlang (local) `<fn>`(`<rlb_rr__>`)
25. handlers[[1L]](cnd)
```
which points to these lines in test-netest.R:
```r
netest_2 <- netest(nw = nw,
formation = ~edges + nodematch(r, diff = TRUE),
target.stats = c(500, 50, 50, 90, 40, 60),
coef.diss = coef_diss,
nested.edapprox = FALSE,
from.new = "a")
```
It seems like `from.new` is passed through correctly to netest's `...`, so I don't think this is a concern. Yet, is there a way we can stop triggering this warning?

Fix unit tests for v2.3.2 push

---

DESCRIPTION
R/EpiModel-package.R
R/netest.R
R/utils.R
man/trim_netest.Rd
man/update_dissolution.Rd
tests/testthat/test-netest.R

stacked on #825
closes #806
Eliminates remaining uses of `nonsimp_update.formula` (and `append_rhs.formula`), avoiding potential issues that can arise with environments when these functions are used to manipulate formulas.
Depends on `master` versions of `ergm`, `ergm.ego`, and `tergm`.

remove nonsimp_update.formula

---

R/net.mod.init.R
tests/testthat/test-netrestart.R

The reinit code in EpiModel now superseeds the `reinit_msm` however, this function behavior is to copy the params from the restart point and not use the ones provided by netsim.
This PR reverts that as it is the  way we modify params for the scenario API (and even without).

On reinit, use provided params

---

R/merge.R

check that the `other` element is not `NULL` before trying to assign a new name to it
fixes https://github.com/EpiModel/EpiModelHPC/issues/41

Fix issue with `other` in `merge.netsim`

---

R/netsim.R

previoulsy if `Inf` was passed to `control$nsteps`, the error would occur in the first call to `set_epi` due to the wrong value passed to `rep(NA, nsteps)`.
This PR makes the error explicit

add a control check for `nsteps`

---

NEWS.md
R/net.accessor.R
R/reachable.R
man/net-accessor.Rd
tests/testthat/test-accessors.R
tests/testthat/test-utils.R

- single `assert_valid_posit_ids` function shared among accessors
- single `assert_valid_time_steps` function shared among accessors
- removal of logical subsetting in accessors
- code reformatting for consistency with the rest of the codebase
- update the tests to reflect the changes
fixes #822

Consolidate arguments checking in accessors

---

NEWS.md
R/net.inputs.R
R/netdx.R
R/netest.R
man/control.net.Rd
man/netdx.Rd
man/netest.Rd

Fixes #904
set `MCMC.maxchanges = Inf` in all `control.*tergm()` calls.

MCMC.maxchanges = Inf
